# Generated by Django 3.0.5 on 2023-11-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20231121_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='id',
        ),
        migrations.AlterField(
            model_name='entry',
            name='no',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
