# Generated by Django 3.0.5 on 2023-11-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20231121_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='no',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, unique=True),
        ),
    ]
