# Generated by Django 3.0.5 on 2023-11-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20231121_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='no',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
